(() => {
  'use strict';
  const API='https://script.google.com/macros/s/AKfycbzeW8vTooOCNEBia3_EMQ10r7BcbakXIwCD4ZaEOUEBOdCXl09tRHj76oxcUcsOKQK0/exec';
  const SK='mothership_hub_warden_session_v1';
  const S={feed:null,ready:false,preview:null,loading:false};
  const $=id=>document.getElementById(id);
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function atleast(v,t){const a=String(v||'0').split('.').map(Number),b=String(t||'0').split('.').map(Number);for(let i=0;i<Math.max(a.length,b.length);i++){if((a[i]||0)>(b[i]||0))return true;if((a[i]||0)<(b[i]||0))return false}return true}
  function jsonp(action,p={}){return new Promise((resolve,reject)=>{const cb='__wv18'+Date.now()+Math.random().toString(36).slice(2),sc=document.createElement('script'),timer=setTimeout(()=>done(new Error('Warden service timed out.')),30000);function done(err,d){clearTimeout(timer);try{delete window[cb]}catch(_){window[cb]=undefined}sc.remove();err?reject(err):resolve(d)}window[cb]=d=>done(null,d);sc.onerror=()=>done(new Error('Could not reach Warden service.'));sc.src=API+'?'+new URLSearchParams({action,callback:cb,...p});document.head.appendChild(sc)})}
  function session(){return localStorage.getItem(SK)||''}
  function installStyles(){if($('wv18style'))return;const x=document.createElement('style');x.id='wv18style';x.textContent=`
    .adjhead{display:flex;justify-content:space-between;gap:10px;align-items:center;flex-wrap:wrap}.adjrow{display:grid;grid-template-columns:160px minmax(190px,1fr) minmax(170px,.8fr) 90px;gap:10px;padding:9px 0;border-top:1px solid #303538;font-size:.8rem;align-items:start}.adjrow:first-child{border-top:0}.adjmodal{position:fixed;inset:0;z-index:1150;background:rgba(0,0,0,.78);display:flex;align-items:center;justify-content:center;padding:18px}.adjshell{width:min(820px,100%);max-height:92vh;overflow:auto;background:var(--bg);border:1px solid var(--line);padding:20px}.adjgrid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:14px}.adjwide{grid-column:1/-1}.adjbefore{white-space:pre-wrap;max-height:160px;overflow:auto;background:var(--panel2);border:1px solid var(--line);padding:10px;margin-top:5px}.adjactions{display:flex;justify-content:flex-end;gap:9px;flex-wrap:wrap;margin-top:18px;padding-top:14px;border-top:1px solid var(--line)}@media(max-width:760px){.adjrow,.adjgrid{grid-template-columns:1fr}.adjwide{grid-column:1}}
  `;document.head.appendChild(x)}
  function installDom(){if($('wardenAdjustPanel'))return;const audit=$('audit')?.closest('.panel');if(!audit)return;const panel=document.createElement('section');panel.id='wardenAdjustPanel';panel.className='panel';panel.innerHTML=`<div class="adjhead"><div><h2 style="margin-bottom:4px">Audited Warden Adjustment</h2><div class="small">Constrained correction tool over existing authoritative state. Derived finance and catalog-definition fields are excluded.</div></div><button id="openAdjustment" class="btn primary" disabled>ADJUST CAMPAIGN STATE</button></div><div id="adjustStatus" class="small" style="margin-top:9px">Backend 6.9+ required.</div><div id="adjustHistory" style="margin-top:10px"></div>`;audit.parentElement.insertBefore(panel,audit);
    const modal=document.createElement('div');modal.id='adjustModal';modal.className='adjmodal hidden';modal.innerHTML=`<div class="adjshell"><div class="mhead"><div><div class="label">AUDITED WARDEN ADJUSTMENT</div><h2>Correct Existing Campaign State</h2><div class="small">Every change records exact before/after state and a required reason. Undo is allowed only while the target still matches the audited after-state.</div></div><button id="adjX" class="btn">×</button></div><div class="adjgrid"><label class="adjwide"><span class="label">TARGET</span><select id="adjTarget" class="select"></select></label><div class="adjwide"><span class="label">CURRENT VALUE</span><div id="adjCurrent" class="adjbefore">—</div><div id="adjContext" class="small"></div></div><label class="adjwide"><span class="label">CORRECTED VALUE</span><textarea id="adjValueText" class="textarea"></textarea><input id="adjValueNumber" class="field hidden" type="number" step="1"></label><label class="adjwide"><span class="label">REASON / SOURCE OF CORRECTION</span><textarea id="adjReason" class="textarea" maxlength="1600" placeholder="Why is this correction necessary, and what establishes the corrected value?"></textarea></label></div><div id="adjResult" class="notice hidden"></div><div id="adjPreviewBox" class="review hidden"></div><div class="adjactions"><button id="adjCancel" class="btn">CANCEL</button><button id="adjPreview" class="btn primary">PREVIEW ADJUSTMENT</button><button id="adjCommit" class="btn primary" disabled>COMMIT ADJUSTMENT</button></div></div>`;document.body.appendChild(modal);
    $('openAdjustment').onclick=openModal;$('adjX').onclick=closeModal;$('adjCancel').onclick=closeModal;$('adjTarget').onchange=targetChanged;$('adjValueText').oninput=invalidate;$('adjValueNumber').oninput=invalidate;$('adjReason').oninput=invalidate;$('adjPreview').onclick=preview;$('adjCommit').onclick=commit;
  }
  function groupedOptions(){const groups={};(S.feed?.targets||[]).forEach(t=>(groups[t.domain]||(groups[t.domain]=[])).push(t));return '<option value="">SELECT AUTHORITATIVE FIELD</option>'+Object.keys(groups).sort().map(g=>`<optgroup label="${esc(g)}">${groups[g].map(t=>`<option value="${esc(t.id)}">${esc(t.label)}</option>`).join('')}</optgroup>`).join('')}
  function target(){return (S.feed?.targets||[]).find(t=>t.id===$('adjTarget').value)||null}
  function targetChanged(){const t=target();$('adjCurrent').textContent=t?String(t.currentValue??''):'—';$('adjContext').textContent=t?.context||'';const num=t?.inputType==='number';$('adjValueNumber').classList.toggle('hidden',!num);$('adjValueText').classList.toggle('hidden',num);if(t){if(num){$('adjValueNumber').min=t.min??0;$('adjValueNumber').max=t.max??20;$('adjValueNumber').value=t.currentValue??''}else $('adjValueText').value=t.currentValue??''}invalidate()}
  function value(){const t=target();return t?.inputType==='number'?$('adjValueNumber').value:$('adjValueText').value}
  function invalidate(){S.preview=null;$('adjCommit').disabled=true;$('adjPreviewBox').classList.add('hidden');$('adjPreviewBox').innerHTML='';$('adjResult').className='notice hidden';$('adjResult').textContent=''}
  function openModal(){if(!S.ready)return;$('adjTarget').innerHTML=groupedOptions();$('adjTarget').value='';$('adjCurrent').textContent='—';$('adjValueText').value='';$('adjValueNumber').value='';$('adjReason').value='';invalidate();$('adjustModal').classList.remove('hidden');document.body.style.overflow='hidden'}
  function closeModal(){$('adjustModal').classList.add('hidden');document.body.style.overflow='';invalidate()}
  async function preview(){const t=target();if(!t){show('Select an adjustment target.','bad');return}try{$('adjPreview').disabled=true;const r=await jsonp('wardenadjustpreview',{session:session(),target:t.id,value:value(),reason:$('adjReason').value});if(!r?.ok)throw new Error(r?.error||'Adjustment preview failed.');S.preview=r;$('adjPreviewBox').innerHTML='<div class="label">PREVIEW</div><ul>'+r.summary.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>';$('adjPreviewBox').classList.remove('hidden');$('adjCommit').disabled=false;show('Preview is current. Commit will write this exact change.','ok')}catch(e){show(e.message||String(e),'bad')}finally{$('adjPreview').disabled=false}}
  async function commit(){if(!S.preview)return;try{$('adjCommit').disabled=true;const t=target();const r=await jsonp('wardenadjustcommit',{session:session(),target:t.id,value:value(),reason:$('adjReason').value,stateToken:S.preview.stateToken});if(!r?.ok)throw new Error(r?.error||'Adjustment commit failed.');show('Adjustment committed: '+r.transactionId,'ok');await loadFeed();setTimeout(closeModal,350)}catch(e){show(e.message||String(e),'bad')}}
  function show(msg,kind){$('adjResult').textContent=msg;$('adjResult').className='notice '+(kind||'warn')}
  async function undo(tx){if(!confirm('Undo audited adjustment '+tx+'?\n\nThis will restore the exact prior value only if no later change touched that target.'))return;try{const r=await jsonp('wardenadjustundo',{session:session(),transaction:tx});if(!r?.ok)throw new Error(r?.error||'Adjustment Undo failed.');await loadFeed()}catch(e){alert(e.message||String(e))}}
  function renderHistory(){const el=$('adjustHistory');if(!el)return;const h=S.feed?.history||[];if(!h.length){el.innerHTML='<div class="empty">NO AUDITED MANUAL ADJUSTMENTS</div>';return}el.innerHTML=h.map(x=>`<div class="adjrow"><div><strong>${esc(x.timestamp||x.campaignDate||'')}</strong><div class="small">${esc(x.transactionId)}</div></div><div><strong>${esc(x.after?.label||x.title||'Adjustment')}</strong><div class="small">${esc(x.reason||'')}</div></div><div><span class="label">BEFORE</span> ${esc(x.before?.value??'')}<br><span class="label">AFTER</span> ${esc(x.after?.value??'')}</div><div>${x.canUndo?`<button class="btn mini danger" data-adjundo="${esc(x.transactionId)}">UNDO</button>`:'<span class="small">UNDONE</span>'}</div></div>`).join('');el.querySelectorAll('[data-adjundo]').forEach(b=>b.onclick=()=>undo(b.dataset.adjundo))}
  async function loadFeed(){if(S.loading)return;const ses=session();if(!ses)return;S.loading=true;try{const r=await jsonp('wardenadjustfeed',{session:ses});if(!r?.ok)throw new Error(r?.error||'Adjustment feed unavailable.');S.feed=r;S.ready=atleast(r.serviceVersion,'6.9');$('openAdjustment').disabled=!S.ready;$('adjustStatus').textContent=S.ready?`${r.targets.length} safe authoritative field target(s) available // BACKEND ${r.serviceVersion} // WARDEN ${r.wardenVersion}`:'Backend 6.9+ required.';renderHistory()}catch(e){S.ready=false;$('openAdjustment').disabled=true;$('adjustStatus').textContent='Adjustment service unavailable until backend 6.9 is deployed.'}finally{S.loading=false}}
  function watch(){document.addEventListener('click',e=>{if(e.target.closest('#refresh'))setTimeout(loadFeed,350);if(e.target.closest('#lock,#playerPage')){closeModal();S.feed=null;S.ready=false}},true);const obs=new MutationObserver(()=>{if(!$('console')?.classList.contains('hidden')&&session())setTimeout(loadFeed,250)});if($('console'))obs.observe($('console'),{attributes:true,attributeFilter:['class']})}
  installStyles();installDom();watch();setTimeout(loadFeed,500);
})();
