(() => {
'use strict';
const API='https://script.google.com/macros/s/AKfycbzeW8vTooOCNEBia3_EMQ10r7BcbakXIwCD4ZaEOUEBOdCXl09tRHj76oxcUcsOKQK0/exec',SK='mothership_hub_warden_session_v1';
const S={feed:null,ready:false,current:null,preview:null,loading:false};
const $=x=>document.getElementById(x),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function atleast(v,t){const a=String(v||'0').split('.').map(Number),b=String(t||'0').split('.').map(Number);for(let i=0;i<Math.max(a.length,b.length);i++){if((a[i]||0)>(b[i]||0))return true;if((a[i]||0)<(b[i]||0))return false}return true}
function session(){return localStorage.getItem(SK)||''}
function jsonp(action,p={}){return new Promise((resolve,reject)=>{const cb='__wv21'+Date.now()+Math.random().toString(36).slice(2),sc=document.createElement('script'),timer=setTimeout(()=>done(new Error('Warden service timed out.')),30000);function done(err,d){clearTimeout(timer);try{delete window[cb]}catch(_){window[cb]=undefined}sc.remove();err?reject(err):resolve(d)}window[cb]=d=>done(null,d);sc.onerror=()=>done(new Error('Could not reach Warden service.'));sc.src=API+'?'+new URLSearchParams({action,callback:cb,...p});document.head.appendChild(sc)})}
function installStyles(){if($('wv21style'))return;const s=document.createElement('style');s.id='wv21style';s.textContent=`.fachead{display:flex;justify-content:space-between;gap:10px;align-items:center;flex-wrap:wrap}.facgrid{display:grid;grid-template-columns:300px 1fr;gap:12px;margin-top:10px}.faclist{max-height:450px;overflow:auto;border:1px solid var(--line);background:var(--panel2)}.facitem{padding:9px 10px;border-top:1px solid #303538;cursor:pointer}.facitem:first-child{border-top:0}.facitem.active{outline:1px solid var(--accent);background:#262a2e}.facdetail{border:1px solid var(--line);background:var(--panel2);padding:12px}.facdims{display:grid;grid-template-columns:repeat(5,1fr);gap:6px;margin-top:8px}.facdim{border:1px solid var(--line);padding:6px;font-size:.72rem}.facpressure{border-top:1px solid var(--line);margin-top:12px;padding-top:10px}.fachistory{display:grid;grid-template-columns:155px minmax(200px,1fr) 90px;gap:10px;padding:8px 0;border-top:1px solid #303538;font-size:.78rem}.facmodal{position:fixed;inset:0;z-index:1180;background:rgba(0,0,0,.78);display:flex;align-items:center;justify-content:center;padding:18px}.facshell{width:min(860px,100%);max-height:92vh;overflow:auto;background:var(--bg);border:1px solid var(--line);padding:20px}.facform{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:14px}.facwide{grid-column:1/-1}.facwarn{border-left:2px solid var(--accent);padding-left:8px;color:var(--muted);margin-top:8px}@media(max-width:760px){.facgrid,.facform,.fachistory{grid-template-columns:1fr}.facwide{grid-column:1}.facdims{grid-template-columns:1fr 1fr}}`;document.head.appendChild(s)}
function installDom(){if($('factionManager'))return;const anchor=$('npcManager')||$('progressionManager')||$('wardenAdjustPanel')||$('audit')?.closest('.panel');if(!anchor)return;const p=document.createElement('section');p.id='factionManager';p.className='panel';p.innerHTML=`<div class="fachead"><div><h2 style="margin-bottom:4px">Faction / Institution Administration</h2><div class="small">Institution-specific evidence remains in Reputation. This layer tracks the canonical five-part pressure model without generic faction points.</div></div><button id="facEdit" class="btn primary" disabled>UPDATE PRESSURE STATE</button></div><div id="facStatus" class="small" style="margin-top:8px">Backend 7.2+ required.</div><div class="facgrid"><div id="facList" class="faclist"></div><div id="facDetail" class="facdetail"><div class="empty">SELECT A FACTION / INSTITUTION</div></div></div><div class="facdetail" style="margin-top:10px"><div class="label">RECENT FACTION / INSTITUTION UPDATES</div><div id="facHistory"></div></div>`;anchor.insertAdjacentElement('afterend',p);
const m=document.createElement('div');m.id='facModal';m.className='facmodal hidden';m.innerHTML=`<div class="facshell"><div class="mhead"><div><div class="label">FACTION PRESSURE MODEL</div><h2 id="facModalTitle">UPDATE</h2><div id="facModalSub" class="small"></div></div><button id="facX" class="btn">×</button></div><div class="facform"><label><span class="label">1. CURRENT NEED</span><textarea id="facNeed" class="textarea"></textarea></label><label><span class="label">2. AVAILABLE LEVERAGE</span><textarea id="facLeverage" class="textarea"></textarea></label><label><span class="label">3. SCARCE RESOURCE / PRIORITY</span><textarea id="facScarcity" class="textarea"></textarea></label><label><span class="label">4. PRIOR FAVOR / INJURY / PROMISE / PRECEDENT</span><textarea id="facPrior" class="textarea"></textarea></label><label class="facwide"><span class="label">5. ACCEPTABLE OUTCOME</span><textarea id="facOutcome" class="textarea"></textarea></label><label class="facwide"><span class="label">OPERATIONAL NOTE</span><textarea id="facNote" class="textarea"></textarea></label><label class="facwide"><span class="label">FACTUAL UPDATE REASON</span><textarea id="facReason" class="textarea"></textarea></label></div><div id="facResult" class="notice hidden"></div><div id="facPreviewBox" class="review hidden"></div><div class="mactions"><button id="facCancel" class="btn">CANCEL</button><button id="facPreview" class="btn primary">PREVIEW</button><button id="facCommit" class="btn primary" disabled>COMMIT</button></div></div>`;document.body.appendChild(m);
$('facEdit').onclick=open;$('facX').onclick=close;$('facCancel').onclick=close;$('facPreview').onclick=preview;$('facCommit').onclick=commit}
function selectFac(name){S.current=(S.feed?.factions||[]).find(x=>x.name===name)||null;renderList();renderDetail();$('facEdit').disabled=!S.ready||!S.current}
function activeRestrictions(x){return(S.feed?.restrictions||[]).filter(r=>String(r.status).toUpperCase()==='ACTIVE'&&(r.scopeValue===x.name||r.scopeValue===x.canonicalName))}
function renderList(){const list=$('facList'),f=S.feed?.factions||[];list.innerHTML=f.length?f.map(x=>`<div class="facitem${S.current?.name===x.name?' active':''}" data-fac="${esc(x.name)}"><strong>${esc(x.canonicalName)}</strong><div class="small">${esc(x.classification)}</div><div class="small">${esc(x.reliability)}/${esc(x.safety)}/${esc(x.workerFairness)}/${esc(x.discretion)}/${esc(x.legalCommercial)}</div></div>`).join(''):'<div class="empty">NO INSTITUTION ROWS</div>';list.querySelectorAll('[data-fac]').forEach(x=>x.onclick=()=>selectFac(x.dataset.fac))}
function renderDetail(){const d=$('facDetail'),x=S.current;if(!x){d.innerHTML='<div class="empty">SELECT A FACTION / INSTITUTION</div>';return}const rs=activeRestrictions(x);d.innerHTML=`<div class="title">${esc(x.canonicalName)}</div><div class="meta">${esc(x.classification)}${x.canonicalName!==x.name?' · LIVE ROW: '+esc(x.name):''}</div>${x.warning?`<div class="facwarn">${esc(x.warning)}</div>`:''}<div style="margin-top:9px"><span class="label">CURRENT ACCESS SUMMARY</span><div>${esc(x.access||'—')}</div></div><div style="margin-top:8px"><span class="label">EARNED PRIVILEGES</span><div>${esc(x.privileges||'—')}</div></div><div style="margin-top:8px"><span class="label">CURRENT RESTRICTIONS</span><div>${esc(x.restrictions||'—')}</div></div><div style="margin-top:8px"><span class="label">NEXT EVIDENCE / TRUST GATE</span><div>${esc(x.nextGate||'—')}</div></div><div class="facdims"><div class="facdim"><span class="label">RELIABILITY</span><br>${esc(x.reliability||'—')}</div><div class="facdim"><span class="label">SAFETY</span><br>${esc(x.safety||'—')}</div><div class="facdim"><span class="label">WORKER FAIRNESS</span><br>${esc(x.workerFairness||'—')}</div><div class="facdim"><span class="label">DISCRETION</span><br>${esc(x.discretion||'—')}</div><div class="facdim"><span class="label">LEGAL / COMMERCIAL</span><br>${esc(x.legalCommercial||'—')}</div></div><div class="facpressure"><div class="label">CURRENT PRESSURE MODEL</div><div><strong>Need:</strong> ${esc(x.currentNeed||'—')}</div><div><strong>Leverage:</strong> ${esc(x.availableLeverage||'—')}</div><div><strong>Scarcity:</strong> ${esc(x.scarceResource||'—')}</div><div><strong>Prior influence:</strong> ${esc(x.priorInfluence||'—')}</div><div><strong>Acceptable outcome:</strong> ${esc(x.acceptableOutcome||'—')}</div><div><strong>Operational note:</strong> ${esc(x.operationalNote||'—')}</div><div class="small">Last operational change: ${esc(x.lastOperationalChange||'—')}</div></div>${rs.length?`<div class="facpressure"><div class="label">ACTIVE CONTRACT RESTRICTIONS</div>${rs.map(r=>`<div>${esc(r.character)} — ${esc(r.restrictionType)}<div class="small">${esc(r.sourceNotes)}</div></div>`).join('')}</div>`:''}<div class="small" style="margin-top:10px">Evidence/access corrections remain available through ADJUST CAMPAIGN STATE. This panel does not create generic Standing.</div>`}
function open(){if(!S.ready||!S.current)return;S.preview=null;$('facCommit').disabled=true;$('facPreviewBox').classList.add('hidden');$('facResult').className='notice hidden';$('facModalTitle').textContent=S.current.canonicalName;$('facModalSub').textContent='need → leverage → scarcity → prior influence → acceptable outcome';$('facNeed').value=S.current.currentNeed||'';$('facLeverage').value=S.current.availableLeverage||'';$('facScarcity').value=S.current.scarceResource||'';$('facPrior').value=S.current.priorInfluence||'';$('facOutcome').value=S.current.acceptableOutcome||'';$('facNote').value=S.current.operationalNote||'';$('facReason').value='';document.querySelectorAll('#facModal textarea').forEach(x=>x.oninput=invalidate);$('facModal').classList.remove('hidden');document.body.style.overflow='hidden'}
function close(){$('facModal').classList.add('hidden');document.body.style.overflow='';S.preview=null}
function invalidate(){S.preview=null;$('facCommit').disabled=true;$('facPreviewBox').classList.add('hidden');$('facResult').className='notice hidden'}
function params(){return{name:S.current.name,currentNeed:$('facNeed').value,availableLeverage:$('facLeverage').value,scarceResource:$('facScarcity').value,priorInfluence:$('facPrior').value,acceptableOutcome:$('facOutcome').value,operationalNote:$('facNote').value,reason:$('facReason').value}}
function show(msg,kind){$('facResult').textContent=msg;$('facResult').className='notice '+kind}
async function preview(){try{$('facPreview').disabled=true;const r=await jsonp('wardenfactionpreview',{session:session(),...params()});if(!r?.ok)throw new Error(r?.error||'Faction Preview failed.');S.preview=r;$('facPreviewBox').innerHTML='<div class="label">PREVIEW</div><ul>'+r.summary.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>';$('facPreviewBox').classList.remove('hidden');$('facCommit').disabled=false;show('Preview current.','ok')}catch(e){show(e.message||String(e),'bad')}finally{$('facPreview').disabled=false}}
async function commit(){if(!S.preview)return;try{$('facCommit').disabled=true;const r=await jsonp('wardenfactioncommit',{session:session(),...params(),stateToken:S.preview.stateToken});if(!r?.ok)throw new Error(r?.error||'Faction update failed.');show('Faction update committed: '+r.transactionId,'ok');const keep=S.current?.name||'';await load();selectFac(keep);setTimeout(close,350)}catch(e){show(e.message||String(e),'bad')}}
async function undo(tx){if(!confirm('Undo faction/institution update '+tx+'?\n\nUndo will refuse if that pressure state changed afterward.'))return;try{const r=await jsonp('wardenfactionundo',{session:session(),transaction:tx});if(!r?.ok)throw new Error(r?.error||'Faction Undo failed.');await load()}catch(e){alert(e.message||String(e))}}
function renderHistory(){const h=S.feed?.history||[];$('facHistory').innerHTML=h.length?h.map(x=>`<div class="fachistory"><div><strong>${esc(x.timestamp)}</strong><div class="small">${esc(x.transactionId)}</div></div><div>${esc(x.title)}<div class="small">${esc(x.reason||'')}</div></div><div>${x.canUndo?`<button class="btn mini danger" data-fundo="${esc(x.transactionId)}">UNDO</button>`:'<span class="small">UNDONE</span>'}</div></div>`).join(''):'<div class="empty">NO FACTION OPERATIONAL UPDATES</div>';$('facHistory').querySelectorAll('[data-fundo]').forEach(b=>b.onclick=()=>undo(b.dataset.fundo))}
async function load(){if(S.loading||!session())return;S.loading=true;const prior=S.current?.name||'';try{const r=await jsonp('wardenfactionfeed',{session:session()});if(!r?.ok)throw new Error(r?.error||'Faction feed unavailable.');S.feed=r;S.ready=atleast(r.serviceVersion,'7.2');$('facStatus').textContent=S.ready?`BACKEND ${r.serviceVersion} // WARDEN ${r.wardenVersion} // ${r.factions.filter(x=>x.classification==='MAJOR FACTION').length} major factions // ${r.factions.filter(x=>x.classification!=='MAJOR FACTION').length} institutions`:'Backend 7.2+ required.';S.current=(r.factions||[]).find(x=>x.name===prior)||(r.factions||[])[0]||null;renderList();renderDetail();renderHistory();$('facEdit').disabled=!S.ready||!S.current}catch(e){S.ready=false;$('facStatus').textContent='Faction Administration requires backend 7.2.';$('facEdit').disabled=true}finally{S.loading=false}}
function watch(){document.addEventListener('click',e=>{if(e.target.closest('#refresh'))setTimeout(load,450);if(e.target.closest('#lock,#playerPage')){close();S.feed=null;S.current=null;S.ready=false}},true);const o=new MutationObserver(()=>{if(!$('console')?.classList.contains('hidden')&&session())setTimeout(load,350)});if($('console'))o.observe($('console'),{attributes:true,attributeFilter:['class']})}
installStyles();installDom();watch();setTimeout(load,1050);
})();
