(() => {
'use strict';
const API='https://script.google.com/macros/s/AKfycbzeW8vTooOCNEBia3_EMQ10r7BcbakXIwCD4ZaEOUEBOdCXl09tRHj76oxcUcsOKQK0/exec';
const SK='mothership_hub_warden_session_v1';
const $=id=>document.getElementById(id);
const cache=new Map();
let requestSeq=0,observer=null,attachTimer=null,lastObservedName='';
function session(){return localStorage.getItem(SK)||''}
function jsonp(action,p={}){return new Promise((resolve,reject)=>{const cb='__wnp25'+Date.now()+Math.random().toString(36).slice(2),sc=document.createElement('script'),timer=setTimeout(()=>done(new Error('NPC portrait request timed out.')),30000);function done(err,d){clearTimeout(timer);try{delete window[cb]}catch(_){window[cb]=undefined}sc.remove();err?reject(err):resolve(d)}window[cb]=d=>done(null,d);sc.onerror=()=>done(new Error('Could not reach Warden portrait service.'));sc.src=API+'?'+new URLSearchParams({action,callback:cb,...p});document.head.appendChild(sc)})}
function installStyles(){if($('npcPortraitStyles'))return;const s=document.createElement('style');s.id='npcPortraitStyles';s.textContent=`.npcportrait-status{margin-top:5px;min-height:1.15em;color:var(--muted);font-size:.7rem}.npcportrait-status.bad{color:var(--danger)}.npcportrait-wrap{margin:12px 0;display:flex;justify-content:flex-start}.npcportrait{display:block;max-width:min(240px,100%);max-height:340px;width:auto;height:auto;object-fit:contain;border:1px solid var(--line);background:#0d0f10}`;document.head.appendChild(s)}
function selected(){const d=$('npcDetail'),t=d?.querySelector('.title');const name=t?.textContent?.trim()||'';return{name,detail:d}}
function statusHost(name){const s=selected();if(!s.detail||s.name!==name)return null;let el=s.detail.querySelector('.npcportrait-status');if(!el){el=document.createElement('div');el.className='npcportrait-status';const meta=s.detail.querySelector('.meta');if(meta)meta.insertAdjacentElement('afterend',el);else s.detail.prepend(el)}return el}
function setStatus(name,text,bad=false){const el=statusHost(name);if(!el)return;el.textContent=text||'';el.className='npcportrait-status'+(bad?' bad':'')}
function insertPortrait(name,dataUri,sourceName){const s=selected();if(!s.detail||s.name!==name||!dataUri)return;let wrap=s.detail.querySelector('.npcportrait-wrap');if(wrap&&wrap.dataset.npcName===name)return;if(wrap)wrap.remove();wrap=document.createElement('div');wrap.className='npcportrait-wrap';wrap.dataset.npcName=name;const img=document.createElement('img');img.className='npcportrait';img.alt=name+' portrait';img.onload=()=>setStatus(name,'PORTRAIT: '+(sourceName||'LOADED'));img.onerror=()=>{wrap.remove();setStatus(name,'PORTRAIT IMAGE DECODE FAILED',true)};img.src=dataUri;wrap.appendChild(img);const facts=s.detail.querySelector('.npcfacts');if(facts)s.detail.insertBefore(wrap,facts);else s.detail.appendChild(wrap)}
function useCached(name,entry){if(!entry)return;setStatus(name,entry.status,entry.bad);if(entry.uri)insertPortrait(name,entry.uri,entry.sourceName)}
async function loadPortrait(force=false){const s=selected();if(!s.detail||!s.name||!session())return;const name=s.name;if(force)cache.delete(name);const existing=s.detail.querySelector('.npcportrait-wrap');if(existing?.dataset.npcName===name&&!force)return;if(existing)existing.remove();if(cache.has(name)){useCached(name,cache.get(name));return}setStatus(name,'PORTRAIT: CHECKING…');const seq=++requestSeq;try{const r=await jsonp('wardennpcportrait',{session:session(),name});if(seq!==requestSeq||selected().name!==name)return;if(!r?.ok){const msg='PORTRAIT BACKEND ERROR: '+String(r?.error||'Unknown error');const entry={uri:null,status:msg,bad:true};cache.set(name,entry);useCached(name,entry);return}if(!r.found){const entry={uri:null,status:'PORTRAIT: NO MATCHING PNG/JPG/JPEG FOUND',bad:false};cache.set(name,entry);useCached(name,entry);return}const uri=r.dataUri?String(r.dataUri):'';if(!uri){const entry={uri:null,status:'PORTRAIT BACKEND RETURNED NO IMAGE DATA',bad:true};cache.set(name,entry);useCached(name,entry);return}const source=String(r.sourceName||'portrait');const bytes=Number(r.thumbnailBytes||0);const entry={uri,status:'PORTRAIT: '+source+(bytes?' // '+bytes.toLocaleString()+' bytes':''),bad:false,sourceName:source};cache.set(name,entry);useCached(name,entry)}catch(e){if(seq!==requestSeq||selected().name!==name)return;const entry={uri:null,status:'PORTRAIT SERVICE ERROR: '+String(e?.message||e),bad:true};cache.set(name,entry);useCached(name,entry)}}
function attachObserver(){const detail=$('npcDetail');if(!detail){clearTimeout(attachTimer);attachTimer=setTimeout(attachObserver,300);return}if(observer)return;lastObservedName=selected().name;observer=new MutationObserver(()=>{const name=selected().name;if(name&&name!==lastObservedName){lastObservedName=name;setTimeout(()=>loadPortrait(false),35)}});observer.observe(detail,{childList:true,subtree:true});loadPortrait(false)}
function clear(){requestSeq++;cache.clear();lastObservedName='';const detail=$('npcDetail');detail?.querySelector('.npcportrait-wrap')?.remove();detail?.querySelector('.npcportrait-status')?.remove()}
installStyles();attachObserver();
document.addEventListener('click',e=>{if(e.target.closest('[data-npc]'))setTimeout(()=>loadPortrait(false),100);if(e.target.closest('#refresh'))setTimeout(()=>loadPortrait(true),180);if(e.target.closest('#lock,#playerPage'))clear()},true);
})();