(() => {
'use strict';
const API='https://script.google.com/macros/s/AKfycbzeW8vTooOCNEBia3_EMQ10r7BcbakXIwCD4ZaEOUEBOdCXl09tRHj76oxcUcsOKQK0/exec',SK='mothership_hub_warden_session_v1';
const S={feed:null,ready:false,current:null,preview:null,loading:false};
const $=x=>document.getElementById(x),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function atleast(v,t){const a=String(v||'0').split('.').map(Number),b=String(t||'0').split('.').map(Number);for(let i=0;i<Math.max(a.length,b.length);i++){if((a[i]||0)>(b[i]||0))return true;if((a[i]||0)<(b[i]||0))return false}return true}
function session(){return localStorage.getItem(SK)||''}
function jsonp(action,p={}){return new Promise((resolve,reject)=>{const cb='__wv20'+Date.now()+Math.random().toString(36).slice(2),sc=document.createElement('script'),timer=setTimeout(()=>done(new Error('Warden service timed out.')),30000);function done(err,d){clearTimeout(timer);try{delete window[cb]}catch(_){window[cb]=undefined}sc.remove();err?reject(err):resolve(d)}window[cb]=d=>done(null,d);sc.onerror=()=>done(new Error('Could not reach Warden service.'));sc.src=API+'?'+new URLSearchParams({action,callback:cb,...p});document.head.appendChild(sc)})}
function installStyles(){if($('wv20style'))return;const s=document.createElement('style');s.id='wv20style';s.textContent=`.npchead{display:flex;justify-content:space-between;gap:10px;align-items:center;flex-wrap:wrap}.npcgrid{display:grid;grid-template-columns:290px 1fr;gap:12px;margin-top:10px}.npclist{max-height:430px;overflow:auto;border:1px solid var(--line);background:var(--panel2)}.npcitem{padding:9px 10px;border-top:1px solid #303538;cursor:pointer}.npcitem:first-child{border-top:0}.npcitem.active{outline:1px solid var(--accent);background:#262a2e}.npcdetail{border:1px solid var(--line);background:var(--panel2);padding:12px}.npcfacts{display:grid;grid-template-columns:1fr 1fr;gap:10px}.npcfacts .wide{grid-column:1/-1}.npcop{border-top:1px solid var(--line);margin-top:12px;padding-top:10px}.npchistory{display:grid;grid-template-columns:155px minmax(200px,1fr) 90px;gap:10px;padding:8px 0;border-top:1px solid #303538;font-size:.78rem}.npcmodal{position:fixed;inset:0;z-index:1170;background:rgba(0,0,0,.78);display:flex;align-items:center;justify-content:center;padding:18px}.npcshell{width:min(820px,100%);max-height:92vh;overflow:auto;background:var(--bg);border:1px solid var(--line);padding:20px}.npcform{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:14px}.npcwide{grid-column:1/-1}@media(max-width:760px){.npcgrid,.npcfacts,.npcform,.npchistory{grid-template-columns:1fr}.npcwide,.npcfacts .wide{grid-column:1}}`;document.head.appendChild(s)}
function installDom(){if($('npcManager'))return;const anchor=$('progressionManager')||$('wardenAdjustPanel')||$('audit')?.closest('.panel');if(!anchor)return;const p=document.createElement('section');p.id='npcManager';p.className='panel';p.innerHTML=`<div class="npchead"><div><h2 style="margin-bottom:4px">NPC Manager</h2><div class="small">Operational state for existing CANON Hub NPC Roster entries. Core canon fields are read-only here.</div></div><button id="npcEdit" class="btn primary" disabled>UPDATE SELECTED NPC</button></div><div id="npcStatus" class="small" style="margin-top:8px">Backend 7.2+ required.</div><div class="npcgrid"><div id="npcList" class="npclist"></div><div id="npcDetail" class="npcdetail"><div class="empty">SELECT AN NPC</div></div></div><div class="npcdetail" style="margin-top:10px"><div class="label">RECENT NPC OPERATIONAL UPDATES</div><div id="npcHistory"></div></div>`;anchor.insertAdjacentElement('afterend',p);
const m=document.createElement('div');m.id='npcModal';m.className='npcmodal hidden';m.innerHTML=`<div class="npcshell"><div class="mhead"><div><div class="label">NPC MANAGER</div><h2 id="npcModalTitle">UPDATE NPC</h2><div id="npcModalSub" class="small"></div></div><button id="npcX" class="btn">×</button></div><div class="npcform"><label class="npcwide"><span class="label">CURRENT STATE</span><textarea id="npcState" class="textarea"></textarea></label><label><span class="label">AVAILABILITY</span><select id="npcAvailability" class="select"><option>UNKNOWN</option><option>AVAILABLE</option><option>LIMITED</option><option>UNAVAILABLE</option></select></label><label><span class="label">LAST CAMPAIGN BEAT</span><textarea id="npcBeat" class="textarea"></textarea></label><label class="npcwide"><span class="label">OPEN OBLIGATION / PRESSURE</span><textarea id="npcObligation" class="textarea"></textarea></label><label class="npcwide"><span class="label">OPERATIONAL NOTES</span><textarea id="npcNotes" class="textarea"></textarea></label><label class="npcwide"><span class="label">FACTUAL UPDATE REASON</span><textarea id="npcReason" class="textarea"></textarea></label></div><div id="npcResult" class="notice hidden"></div><div id="npcPreviewBox" class="review hidden"></div><div class="mactions"><button id="npcCancel" class="btn">CANCEL</button><button id="npcPreview" class="btn primary">PREVIEW</button><button id="npcCommit" class="btn primary" disabled>COMMIT</button></div></div>`;document.body.appendChild(m);
$('npcEdit').onclick=open;$('npcX').onclick=close;$('npcCancel').onclick=close;$('npcPreview').onclick=preview;$('npcCommit').onclick=commit}
function selectNpc(name){S.current=(S.feed?.npcs||[]).find(x=>x.name===name)||null;renderList();renderDetail();$('npcEdit').disabled=!S.ready||!S.current}
function renderList(){const list=$('npcList'),n=S.feed?.npcs||[];list.innerHTML=n.length?n.map(x=>`<div class="npcitem${S.current?.name===x.name?' active':''}" data-npc="${esc(x.name)}"><strong>${esc(x.name)}</strong><div class="small">${esc(x.role)} · ${esc(x.faction)}</div><div class="small">${esc(x.availability||'UNKNOWN')} ${x.currentState?'· '+esc(x.currentState):''}</div></div>`).join(''):'<div class="empty">NO CANON NPCS</div>';list.querySelectorAll('[data-npc]').forEach(x=>x.onclick=()=>selectNpc(x.dataset.npc))}
function renderDetail(){const d=$('npcDetail'),x=S.current;if(!x){d.innerHTML='<div class="empty">SELECT AN NPC</div>';return}d.innerHTML=`<div class="title">${esc(x.name)}</div><div class="meta">${esc(x.authorityStatus)} · ${esc(x.knowledge)} · ${esc(x.location)}</div><div class="npcfacts"><div><span class="label">ROLE</span><div>${esc(x.role)}</div></div><div><span class="label">FACTION / INSTITUTION</span><div>${esc(x.faction)}</div></div><div class="wide"><span class="label">CORE PERSONALITY</span><div>${esc(x.corePersonality)}</div></div><div class="wide"><span class="label">ROLEPLAYING MANNER</span><div>${esc(x.roleplayingManner)}</div></div><div><span class="label">MOTIVATION</span><div>${esc(x.motivation)}</div></div><div><span class="label">PRESSURE / FEAR</span><div>${esc(x.pressureFear)}</div></div><div><span class="label">LEVERAGE / OFFER</span><div>${esc(x.leverage)}</div></div><div><span class="label">IMMEDIATE NEED</span><div>${esc(x.immediateNeed)}</div></div></div><div class="npcop"><div class="label">CURRENT OPERATIONAL STATE</div><div><strong>${esc(x.currentState||'—')}</strong></div><div class="small">Availability: ${esc(x.availability||'UNKNOWN')} · Last updated: ${esc(x.lastUpdated||'—')}</div><div style="margin-top:7px"><span class="label">LAST CAMPAIGN BEAT</span><div>${esc(x.lastCampaignBeat||'—')}</div></div><div style="margin-top:7px"><span class="label">OPEN OBLIGATION / PRESSURE</span><div>${esc(x.openObligation||'—')}</div></div><div style="margin-top:7px"><span class="label">OPERATIONAL NOTES</span><div>${esc(x.operationalNotes||'—')}</div></div></div><div class="small" style="margin-top:10px">Detail status: ${esc(x.detailStatus||'—')}<br>Primary source: ${esc(x.primarySource||'—')}</div>`}
function open(){if(!S.current||!S.ready)return;S.preview=null;$('npcCommit').disabled=true;$('npcPreviewBox').classList.add('hidden');$('npcResult').className='notice hidden';$('npcModalTitle').textContent=S.current.name;$('npcModalSub').textContent=S.current.role+' · '+S.current.faction;$('npcState').value=S.current.currentState||'';$('npcAvailability').value=(S.current.availability||'UNKNOWN').toUpperCase();if(!['UNKNOWN','AVAILABLE','LIMITED','UNAVAILABLE'].includes($('npcAvailability').value))$('npcAvailability').value='UNKNOWN';$('npcBeat').value=S.current.lastCampaignBeat||'';$('npcObligation').value=S.current.openObligation||'';$('npcNotes').value=S.current.operationalNotes||'';$('npcReason').value='';document.querySelectorAll('#npcModal input,#npcModal textarea,#npcModal select').forEach(x=>x.oninput=invalidate);$('npcModal').classList.remove('hidden');document.body.style.overflow='hidden'}
function close(){$('npcModal').classList.add('hidden');document.body.style.overflow='';S.preview=null}
function invalidate(){S.preview=null;$('npcCommit').disabled=true;$('npcPreviewBox').classList.add('hidden');$('npcResult').className='notice hidden'}
function params(){return{name:S.current.name,currentState:$('npcState').value,availability:$('npcAvailability').value,lastCampaignBeat:$('npcBeat').value,openObligation:$('npcObligation').value,operationalNotes:$('npcNotes').value,reason:$('npcReason').value}}
function show(msg,kind){$('npcResult').textContent=msg;$('npcResult').className='notice '+kind}
async function preview(){try{$('npcPreview').disabled=true;const r=await jsonp('wardennpcpreview',{session:session(),...params()});if(!r?.ok)throw new Error(r?.error||'NPC Preview failed.');S.preview=r;$('npcPreviewBox').innerHTML='<div class="label">PREVIEW</div><ul>'+r.summary.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>';$('npcPreviewBox').classList.remove('hidden');$('npcCommit').disabled=false;show('Preview current.','ok')}catch(e){show(e.message||String(e),'bad')}finally{$('npcPreview').disabled=false}}
async function commit(){if(!S.preview)return;try{$('npcCommit').disabled=true;const r=await jsonp('wardennpccommit',{session:session(),...params(),stateToken:S.preview.stateToken});if(!r?.ok)throw new Error(r?.error||'NPC update failed.');show('NPC update committed: '+r.transactionId,'ok');await load();selectNpc(S.current?.name||'');setTimeout(close,350)}catch(e){show(e.message||String(e),'bad')}}
async function undo(tx){if(!confirm('Undo NPC operational update '+tx+'?\n\nUndo will refuse if that NPC operational state changed afterward.'))return;try{const r=await jsonp('wardennpcundo',{session:session(),transaction:tx});if(!r?.ok)throw new Error(r?.error||'NPC Undo failed.');await load()}catch(e){alert(e.message||String(e))}}
function renderHistory(){const h=S.feed?.history||[];$('npcHistory').innerHTML=h.length?h.map(x=>`<div class="npchistory"><div><strong>${esc(x.timestamp)}</strong><div class="small">${esc(x.transactionId)}</div></div><div>${esc(x.title)}<div class="small">${esc(x.reason||'')}</div></div><div>${x.canUndo?`<button class="btn mini danger" data-nundo="${esc(x.transactionId)}">UNDO</button>`:'<span class="small">UNDONE</span>'}</div></div>`).join(''):'<div class="empty">NO NPC OPERATIONAL UPDATES</div>';$('npcHistory').querySelectorAll('[data-nundo]').forEach(b=>b.onclick=()=>undo(b.dataset.nundo))}
async function load(){if(S.loading||!session())return;S.loading=true;const prior=S.current?.name||'';try{const r=await jsonp('wardennpcfeed',{session:session()});if(!r?.ok)throw new Error(r?.error||'NPC feed unavailable.');S.feed=r;S.ready=atleast(r.serviceVersion,'7.2');$('npcStatus').textContent=S.ready?`BACKEND ${r.serviceVersion} // WARDEN ${r.wardenVersion} // ${r.npcs.length} CANON NPCs // ${r.excluded.length} non-CANON rows excluded`:'Backend 7.2+ required.';S.current=(r.npcs||[]).find(x=>x.name===prior)||(r.npcs||[])[0]||null;renderList();renderDetail();renderHistory();$('npcEdit').disabled=!S.ready||!S.current}catch(e){S.ready=false;$('npcStatus').textContent='NPC Manager requires backend 7.2.';$('npcEdit').disabled=true}finally{S.loading=false}}
function watch(){document.addEventListener('click',e=>{if(e.target.closest('#refresh'))setTimeout(load,400);if(e.target.closest('#lock,#playerPage')){close();S.feed=null;S.current=null;S.ready=false}},true);const o=new MutationObserver(()=>{if(!$('console')?.classList.contains('hidden')&&session())setTimeout(load,300)});if($('console'))o.observe($('console'),{attributes:true,attributeFilter:['class']})}
installStyles();installDom();watch();setTimeout(load,850);
})();
