(() => {
'use strict';
const API='https://script.google.com/macros/s/AKfycbzeW8vTooOCNEBia3_EMQ10r7BcbakXIwCD4ZaEOUEBOdCXl09tRHj76oxcUcsOKQK0/exec';
const SK='mothership_hub_warden_session_v1';
const $=id=>document.getElementById(id);
const portraitCache=new Map();
const pending=new Map();
const npcMeta=new Map();
let observer=null,attachTimer=null,feedLoading=false,manifestLoading=false,prefetchRunning=false,prefetchGeneration=0;
function session(){return localStorage.getItem(SK)||''}
function atleast(v,t){const a=String(v||'0').split('.').map(Number),b=String(t||'0').split('.').map(Number);for(let i=0;i<Math.max(a.length,b.length);i++){if((a[i]||0)>(b[i]||0))return true;if((a[i]||0)<(b[i]||0))return false}return true}
function jsonp(action,p={}){return new Promise((resolve,reject)=>{const cb='__wnp26'+Date.now()+Math.random().toString(36).slice(2),sc=document.createElement('script'),timer=setTimeout(()=>done(new Error('NPC portrait request timed out.')),30000);function done(err,d){clearTimeout(timer);try{delete window[cb]}catch(_){window[cb]=undefined}sc.remove();err?reject(err):resolve(d)}window[cb]=d=>done(null,d);sc.onerror=()=>done(new Error('Could not reach Warden service.'));sc.src=API+'?'+new URLSearchParams({action,callback:cb,...p});document.head.appendChild(sc)})}
async function portraitRequest(name,refresh=false){const params={session:session(),name,...(refresh?{refresh:'1'}:{})};let r=await jsonp('wardennpcportrait',params);if(!refresh&&r?.ok&&!r?.found)r=await jsonp('wardennpcportrait',{...params,refresh:'1'});return r}
function releaseEntry(entry){if(entry?.objectUrl){try{URL.revokeObjectURL(entry.objectUrl)}catch(_){}}}
function clearPortraitCache(){portraitCache.forEach(releaseEntry);portraitCache.clear()}
function portraitEntryFromResponse(r){if(!r?.found||!r?.dataUri)return{uri:null,sourceName:String(r?.sourceName||''),found:Boolean(r?.found),hasData:Boolean(r?.dataUri)};const raw=String(r.dataUri);const marker=';base64,';const markerAt=raw.indexOf(marker);if(!raw.startsWith('data:')||markerAt<5)return{uri:raw,sourceName:String(r.sourceName||''),objectUrl:'',found:true,hasData:true};const mime=String(r.mimeType||raw.slice(5,markerAt)||'image/jpeg');const encoded=raw.slice(markerAt+marker.length);const binary=atob(encoded);const bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);const objectUrl=URL.createObjectURL(new Blob([bytes],{type:mime}));return{uri:objectUrl,sourceName:String(r.sourceName||''),objectUrl,mimeType:mime,byteLength:bytes.length,found:true,hasData:true}}
function installStyles(){if($('npcPortraitStyles'))return;const s=document.createElement('style');s.id='npcPortraitStyles';s.textContent=`.npcportrait-status{margin-top:5px;min-height:1.1em;color:var(--muted);font-size:.7rem}.npcportrait-status.bad{color:var(--danger)}.npcportrait-wrap{margin:12px 0;display:flex;justify-content:flex-start}.npcportrait{display:block;max-width:min(240px,100%);max-height:340px;width:auto;height:auto;object-fit:contain;border:1px solid var(--line);background:#0d0f10}`;document.head.appendChild(s)}
function selected(){const detail=$('npcDetail'),title=detail?.querySelector('.title');return{name:title?.textContent?.trim()||'',detail}}
function statusHost(name){const s=selected();if(!s.detail||s.name!==name)return null;let el=s.detail.querySelector('.npcportrait-status');if(!el){el=document.createElement('div');el.className='npcportrait-status';const meta=s.detail.querySelector('.meta');if(meta)meta.insertAdjacentElement('afterend',el);else s.detail.prepend(el)}return el}
function setStatus(name,text,bad=false){const el=statusHost(name);if(!el)return;el.textContent=text||'';el.className='npcportrait-status'+(bad?' bad':'')}
function clearStatus(name){const s=selected();if(s.name!==name)return;s.detail?.querySelector('.npcportrait-status')?.remove()}
function insertPortrait(name,entry){const s=selected();if(!s.detail||s.name!==name||!entry?.uri)return;let wrap=s.detail.querySelector('.npcportrait-wrap');if(wrap?.dataset?.npcName===name)return;if(wrap)wrap.remove();wrap=document.createElement('div');wrap.className='npcportrait-wrap';wrap.dataset.npcName=name;const img=document.createElement('img');img.className='npcportrait';img.alt=name+' portrait';img.decoding='async';const stalled=setTimeout(()=>{if(!img.complete)setStatus(name,'PORTRAIT IMAGE LOAD STALLED',true)},8000);img.onload=()=>{clearTimeout(stalled);clearStatus(name)};img.onerror=()=>{clearTimeout(stalled);wrap.remove();setStatus(name,'PORTRAIT IMAGE DECODE FAILED',true)};img.src=entry.uri;wrap.appendChild(img);const facts=s.detail.querySelector('.npcfacts');if(facts)s.detail.insertBefore(wrap,facts);else s.detail.appendChild(wrap)}
function annotateHeaderMeta(name){const s=selected();if(!s.detail||s.name!==name)return;const el=s.detail.querySelector('.meta'),meta=npcMeta.get(name);if(!el||!meta)return;const authority=String(meta.authorityStatus||'—').trim()||'—',knowledge=String(meta.knowledge||'—').trim()||'—',location=String(meta.location||'—').trim()||'—';el.textContent=`AUTHORITY: ${authority} · KNOWLEDGE: ${knowledge} · PRIMARY LOCATION: ${location}`}
function annotateCulturalOrigin(name){const s=selected();if(!s.detail||s.name!==name)return;const facts=s.detail.querySelector('.npcfacts');if(!facts)return;const meta=npcMeta.get(name),value=String(meta?.culturalOrigin||'').trim();const prior=facts.querySelector('.npccultural-origin');if(!value){if(prior)prior.remove();return}if(prior&&prior.dataset.npcName===name&&prior.querySelector('div')?.textContent===value)return;if(prior)prior.remove();const box=document.createElement('div');box.className='npccultural-origin';box.dataset.npcName=name;box.innerHTML='<span class="label">CULTURAL / ANCESTRAL ORIGIN</span><div></div>';box.querySelector('div').textContent=value;const factionLabel=[...facts.children].find(x=>x.querySelector?.('.label')?.textContent?.trim()==='FACTION / INSTITUTION');if(factionLabel)factionLabel.insertAdjacentElement('afterend',box);else facts.prepend(box)}
async function requestPortrait(name,{refresh=false,foreground=false}={}){if(!name||!session())return null;if(refresh){releaseEntry(portraitCache.get(name));portraitCache.delete(name)}if(!refresh&&portraitCache.has(name)){const cached=portraitCache.get(name);if(cached?.uri)return cached;portraitCache.delete(name)}if(pending.has(name))return pending.get(name);if(foreground)setStatus(name,'PORTRAIT: LOADING…');const p=(async()=>{try{const r=await portraitRequest(name,refresh);if(!r?.ok)throw new Error(r?.error||'Portrait backend error.');const entry=portraitEntryFromResponse(r);if(entry.uri)portraitCache.set(name,entry);else portraitCache.delete(name);if(foreground){if(entry.uri)insertPortrait(name,entry);else setStatus(name,`PORTRAIT LOOKUP: FOUND=${entry.found?'YES':'NO'} · DATA=${entry.hasData?'YES':'NO'}${entry.sourceName?' · '+entry.sourceName:''}`,true)}return entry}catch(e){portraitCache.delete(name);const entry={uri:null,error:String(e?.message||e)};if(foreground)setStatus(name,'PORTRAIT ERROR: '+entry.error,true);return entry}finally{pending.delete(name)}})();pending.set(name,p);return p}
async function syncSelected({refresh=false}={}){const s=selected();if(!s.name||!s.detail||!session())return;annotateHeaderMeta(s.name);annotateCulturalOrigin(s.name);const existing=s.detail.querySelector('.npcportrait-wrap');if(existing?.dataset?.npcName===s.name&&!refresh)return;if(existing)existing.remove();const cached=!refresh&&portraitCache.get(s.name);if(cached?.uri){insertPortrait(s.name,cached);return}if(cached)portraitCache.delete(s.name);await requestPortrait(s.name,{refresh,foreground:true})}
async function loadNpcMeta(){if(feedLoading||!session())return;feedLoading=true;try{const r=await jsonp('wardennpcfeed',{session:session()});if(r?.ok){npcMeta.clear();(r.npcs||[]).forEach(x=>npcMeta.set(String(x.name||''),x));syncSelected()}}catch(_){/* base NPC Manager owns feed errors */}finally{feedLoading=false}}
function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
async function runPrefetch(names,generation){if(prefetchRunning)return;prefetchRunning=true;try{for(const name of names){if(generation!==prefetchGeneration||!session())break;if(!name||portraitCache.has(name)||pending.has(name))continue;if(selected().name===name)continue;const entry=await requestPortrait(name,{foreground:false});if(!entry?.uri)portraitCache.delete(name);await sleep(300)}}finally{prefetchRunning=false}}
async function loadManifest({refresh=false}={}){if(manifestLoading||!session())return;manifestLoading=true;const generation=++prefetchGeneration;try{const r=await jsonp('wardennpcportraitmanifest',{session:session(),...(refresh?{refresh:'1'}:{})});if(!r?.ok||!atleast(r.serviceVersion,'7.7'))return;const names=(r.available||[]).map(x=>String(x.name||'')).filter(Boolean);setTimeout(()=>runPrefetch(names,generation),650)}catch(_){/* selected portrait still works without manifest */}finally{manifestLoading=false}}
function attachObserver(){const detail=$('npcDetail');if(!detail){clearTimeout(attachTimer);attachTimer=setTimeout(attachObserver,300);return}if(observer)return;observer=new MutationObserver(()=>setTimeout(()=>syncSelected(),30));observer.observe(detail,{childList:true,subtree:true});syncSelected()}
function clearAll(){prefetchGeneration++;clearPortraitCache();pending.clear();npcMeta.clear();const d=$('npcDetail');d?.querySelector('.npcportrait-wrap')?.remove();d?.querySelector('.npcportrait-status')?.remove();d?.querySelector('.npccultural-origin')?.remove()}
function warm(){if(!session())return;loadNpcMeta();loadManifest();setTimeout(()=>syncSelected(),250)}
installStyles();attachObserver();
document.addEventListener('click',e=>{if(e.target.closest('[data-npc]'))setTimeout(()=>syncSelected(),75);if(e.target.closest('#refresh')){prefetchGeneration++;clearPortraitCache();pending.clear();setTimeout(()=>{loadNpcMeta();loadManifest({refresh:true});syncSelected({refresh:true})},180)}if(e.target.closest('#lock,#playerPage'))clearAll()},true);
const consoleEl=$('console');if(consoleEl)new MutationObserver(()=>{if(!consoleEl.classList.contains('hidden'))setTimeout(warm,350);else clearAll()}).observe(consoleEl,{attributes:true,attributeFilter:['class']});
setTimeout(warm,1100);
})();
